[custom.all.parser]
type = "local"
path = "."
ipkg = "parser.ipkg"
test = "test/test.ipkg"

[custom.all.parser-docs]
type = "local"
path = "docs"
ipkg = "docs.ipkg"

[custom.all.parser-test]
type = "local"
path = "test"
ipkg = "test.ipkg"

[custom.all.parser-profile]
type = "local"
path = "profile"
ipkg = "profile.ipkg"

[custom.all.parser-bytestring]
type = "local"
path = "bytestring"
ipkg = "parser-bytestring.ipkg"

[custom.all.parser-toml]
type = "local"
path = "toml"
ipkg = "parser-toml.ipkg"
test = "test/test.ipkg"

[custom.all.parser-toml-test]
type = "local"
path = "toml/test"
ipkg = "test.ipkg"

[custom.all.parser-json]
type = "local"
path = "json"
ipkg = "parser-json.ipkg"
test = "test/test.ipkg"

[custom.all.parser-json-test]
type = "local"
path = "json/test"
ipkg = "test.ipkg"

[custom.all.parser-tsv]
type = "local"
path = "tsv"
ipkg = "parser-tsv.ipkg"
test = "test/test.ipkg"

[custom.all.parser-tsv-test]
type = "local"
path = "tsv/test"
ipkg = "test.ipkg"

[custom.all.parser-webidl]
type = "local"
path = "webidl"
ipkg = "parser-webidl.ipkg"
test = "test/test.ipkg"

[custom.all.parser-webidl-test]
type = "local"
path = "webidl/test"
ipkg = "test.ipkg"

[custom.all.parser-show]
type = "local"
path = "show"
ipkg = "parser-show.ipkg"
test = "test/test.ipkg"

[custom.all.parser-show-test]
type = "local"
path = "show/test"
ipkg = "test.ipkg"

[custom.all.bytestring]
type   = "git"
url    = "git@github.com:stefan-hoeck/idris2-bytestring"
commit = "latest:main"
ipkg   = "bytestring.ipkg"
